language: node_js
os: linux
node_js:
    - 14.15.4
stages:
  - build
  - test
  - deploy

# 需要的数据库
services: 
    - mongodb 
    - redis
    - docker
install:
    - npm i
cache: npm
# 设置邮件通知
notifications:
  email:
    recipients:
        - 619731121@qq.com
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - test
    - develop        

job:
    - stage: build
        script:
            - echo "$DOCKERUSER will build images"
            - docker login -u ${DOCKERUSER} --password ${DOCKERPASSWORD}
            - IMAGENAME=${DOCKERUSER}/deploy
            - echo $IMAGENAME
            - docker build  -t ${IMAGENAME} .
            - docker push ${IMAGENAME}
    - stage: test
        script:
            - echo "this is test stage"
            - npm run lint
            - npm run test
        after_failure:
            - node -pe "require('./test/init.js').dropCollection()"
        after_success:
            - npm run nyc:cov
            - npm run cov 
    - stage: deploy
        script:
            - echo "this is deploy stage"

# 服务器地址
addons:
    ssh_known_hosts: 47.115.164.70
after_success:
    - ssh root@47.115.164.70  "/cribug/deploy.sh"

# 进入服务器密钥
before_install:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
   -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
