name: cribug docker build
on: push
env: 
  IMAGENAME: "cribug"

jobs:
   test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - run: npm run lint
    - run: npm run test
    - run: npm cov

    build: 
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Login Docker
          run:
            echo ${{DOCKERUSER}} ${{DOCKERPASSWORD}} ${{IMAGENAME}}
            docker login -u ${{DOCKERUSER}} --password ${{DOCKERPASSWORD}}
        - name: build images
          run:
            echo $IMAGENAME
            docker build  -t ${{IMAGENAME}} .
            docker push ${{DOCKERUSER}}/${{IMAGENAME}}

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: deploy
          run: echo "this is deploy stage"
