name: cribug docker build
strategy:
  matrix:
    node-version: [14.x]
on: push
env: 
  IMAGENAME: "cribug"

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Login Docker
          run: 
            docker login -u ${DOCKERUSER} --password ${DOCKERPASSWORD}
        - name: build images
          run: |
            echo $IMAGENAME
            docker build  -t ${IMAGENAME} .
            docker push ${IMAGENAME}
    test:
      runs-on: ubuntu-latest
      needs: build
        steps:
        - name: install dependencies
          run: npm i
        - nmae: run test
          run: |
            echo "this is test stage"
            npm run lint
            npm run test
            npm run nyc:cov
            npm run cov 
     stage: deploy
        runs-on: ubuntu-latest
        script:
            - echo "this is deploy stage"
