name: cribug docker build
on: push
env: 
  IMAGENAME: "cribug"

jobs:
    build: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - name: Login Docker
          run: 
            docker login -u ${DOCKERUSER} --password ${DOCKERPASSWORD}
        - name: build images
          run: |
            echo $IMAGENAME
            docker build  -t ${IMAGENAME} .
            docker push ${IMAGENAME}
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: install dependencies
          run: npm i
        - nmae: run lint
          run: npm run lint
        - nmae: run test
          run: npm run test
        - nmae: run cov
          run: npm run cov 
    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - echo "this is deploy stage"
