name: cribug docker build
on: push
env: 
  IMAGENAME: "cribug"

jobs:
    build: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - name: Publish to Docker Repository
        - name: Login Docker
          run: |
            echo ${{DOCKERUSER}} ${{DOCKERPASSWORD}} ${{IMAGENAME}}
            docker login -u ${{DOCKERUSER}} --password ${{DOCKERPASSWORD}}
        - name: build images
          run: |
            echo $IMAGENAME
            docker build  -t ${{IMAGENAME}} .
            docker push ${{DOCKERUSER}}/${{IMAGENAME}}
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: install dependencies
          run: npm i
        - name: run lint
          run: npm run lint
        - name: run test
          run: npm run test
        - name: run cov
          run: npm run cov 
    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: deploy
          run: echo "this is deploy stage"
